### ISSUE TITLE
Milestone Minimize, Project Update

### ISSUE THREAD

**Issue by SimulatedGREG** [SimulatedGREG/electron-vue#171]
## Thank You.

Wow, thank you guys so much for helping make electron-vue one of the top 3 `vue-cli` templates (that I can find) on GitHub. I never thought this project would ever take off like it has today. Thinking back, I originally made this boilerplate (in **May 2016**) for a personal closed sourced project and decided to open source (the boilerplate itself) when I knew I had a majority of the pieces together. Fast-forward almost a full year and there have been so many new features implemented and amazing support from the community. I also want to give a special shoutout to those in the community helping answer issues when I'm not able to. You guys have absolutely no obligation to do anything but you do anyway, and I am grateful for that.

## A Quick Update

So aside from expressing my appreciation, I would like to give a little update. You may or may not have noticed, but I have been away from the project for a few months now and haven't pushed many updates or changes. I've usually been on top of closing issues within a few days of receiving them, but now there are currently 16 open issues! Anyways, in short I recently started a full time position as a UI/UX Engineer working with Vue.js (of course). It has easily taken a lot of my time, but I believe that I am finally back to a steady schedule and feel more confident about maintaining electron-vue once again on a consistent pace. On a related note, I have a lot of credit to give this project for getting me the job as well. So let's talk about what's coming up...

# Milestone: [Minimize](https://github.com/SimulatedGREG/electron-vue/milestone/2)

The main premise of **Minimize** is to move the project structure to a single `package.json` setup. This was not possible back when I started this boilerplate, but thanks to community efforts both `electron-packager` and `electron-builder` now support these setups. Along with this, efforts will be made to rewrite development and build scripts to provide better feedback and reliability. Please feel free to comment below any questions or suggestions; your feedback is everything to this project. 

Features will be merged to `dev` upon competition and can be tested out with...
```bash
vue init simulatedgreg/electron-vue#dev my-project
```

### Upcoming Features

- [x] Single `package.json` structure #112 
- [x] Replace `vue-resource` with `axios` #152 
- [x] Default to Runtime + Compiler build of Vue.js #168 
- [x] Support Web output #128 
- [x] Include AppVeyor/Travis CI configurations for `electron-builder` users #141 
- [x] Newly designed first-run landing page
- [x] Update development environment to conform to [`vuejs-templates/webpack`](https://github.com/vuejs-templates/webpack)'s direction
- [x] Rewrite development scripts to provide better feedback on warning/errors, and possibly give direction to potential solutions (similar to the helpful error messages provided by Vue.js when developing)
  **`feat/dev-scripts`**
  - [x] Start both `main` & `renderer` webpack processes
  - [x] Start `electron` process once both webpack processes are ready
  - [x] Enable hot-reloading in `renderer` process for developing `vue` application
  - [x] Restart `main` process when `main` process webpack rebuilds
  - [x] Push all console messages (**from all 3 processes**) to one terminal in an organized and meaningful way
  - [x] Implement better build step that can stop build process when problems occur and provide error messages 
- ~~Support `main` process debugging #149~~ (`electron@^1.7.2` will be adding support for Node's Inspector Agent, making this process super simple with Chrome) [[electron/electron#6634](https://github.com/electron/electron/issues/6634)]
- [x] Replace UglifyJS with Babili to better target es2015 features available in Node 7/Chromium (removes the need to transpile completely to ES5) #175 
- [x] ~~Scaffolding option~~ Auto update functionality for `electron-builder` users (community suggestion) [@abishekrsrikaanth] 

### Bugfix
- ~~Ensure dependencies are treated as `externals` in testing environments #170~~ (**`karma-webpack`** issue)
- [x] Ensure main process environment better matches in development and production

### Documentation Updates
- [x] Multi-lingual support (Chinese, Japanese) [looking for volunteers] #155 
- [x] Describe use of local filesystem for static assets #165 
- [x] Add more FAQs related to most recently closed issues
-  ~~Add use cases of adding pre-processor loaders #163~~
- [x] Migration guide (community suggestion) [@abishekrsrikaanth] 
- [x] Describe usage with component libraries that have pure `*.vue` files #142 
- [x] Recommend the use of `yarn` package manager 

### Extras
- ~~Project examples (similar to https://vuejs.org/v2/examples/index.html, but more focused on `electron` capabilities)~~ [SoC]
- [x] Featured Community Projects (links to real world projects that the community has made with electron-vue)

**Once again, please feel free to comment any questions or suggestions below.**

**Comment by abishekrsrikaanth** [comment]
@SimulatedGREG, This is a pretty good plan. I would like to suggest the following to this list:
- Migration guide for existing projects to move to the new structure.
- Template configurations for Crash Reporter on the new structure
- Template configurations to setup auto updates if required by an application.

**Comment by rdpascua** [comment]
It would be very useful to know how to use node modules in the projects, like using sqlite in vue-electron.

**Comment by SimulatedGREG** [comment]
@abishekrsrikaanth
Thanks for your suggestions! Could you expand what you mean by adding a Crash Reporter?

@rdpascua
I plan to add items like this in the project examples. Great suggestion!

**Comment by abishekrsrikaanth** [comment]
@SimulatedGREG Electron Supports the Crash Reporter out of the box, but with the current structure, IMO, I am quite confused on what is the best practice to set this up. If the code for this is already setup on the Base Code Template ( could  be commented out or not). It might be easy to configure the crash reporter as required by the developer.

**Comment by SimulatedGREG** [comment]
@abishekrsrikaanth 

The Crash Reporter baked into `electron` isn't super extensive to set up manually so I'll be leaving this one out.

**Comment by abishekrsrikaanth** [comment]
Converted my existing application to use the new #dev branch. 
1. Everything seems to work perfectly in terms of development and running the application for development.
2. Converted to `axios` all good. 
3. Used the `electron-builder` for the first time to generate a build for testing. Doesn't set the env to `production`. I have been use the packager before, but started using the builder for this one. Not sure if I am missing something in terms of configuration that changes the environment.

**Comment by SimulatedGREG** [comment]
@abishekrsrikaanth 

Thanks for the feedback, and glad to hear the switch to `axios` was simple. I believe to have found the issue with the environment not being set to `production` as well. Any issues related to `dev` branch can be posted here.

**Comment by SimulatedGREG** [comment]
Okay, so I've been rewriting the development scripts and having trouble finding a clean solution. Here's what I'm wanting the end product to do...

- [x] Start both `main` & `renderer` webpack processes
- [x] Start `electron` process once both webpack processes are ready
- [x] Enable hot-reloading in `renderer` process for developing `vue` application
- [x] Restart `main` process when `main` process webpack rebuilds
- [ ] Push all console messages (**from all 3 processes**) to one terminal in an organized and meaningful way 

I've been experimenting with using `chalk` and trying to surround each process's console logs with starting and ending blocks, but it doesn't really feel like the cleanest approach to this problem. I've also brought in [`friendly-errors-webpack-plugin`](https://github.com/geowarin/friendly-errors-webpack-plugin) that's found in the official `vuejs-templates/webpack` template. This plugin alone is the main inspiration for making something clean. I'm also considering forking this plugin to make it work without the need of `webpack` so it can be manually fed inputs to process. There is also potential for trying out [`blessed-vue`](https://github.com/lyonlai/blessed-vue).

If you are interested, you can take a look at the current state in the [`feat/dev-scripts`](https://github.com/SimulatedGREG/electron-vue/blob/feat/dev-scripts/template/.electron-vue/dev-runner.js) branch and can try with...
```bash
vue init simulatedgreg/electron-vue#feat/dev-scripts my-project
```

Please feel free to leave any suggestions down below.

**Comment by abishekrsrikaanth** [comment]
👍 for `friendly-errors-webpack-plugin`

Going to give the new branch a try, but came across a peculiar issue, not sure if this is related to `vue-electron` or not.

1. Create a fresh `vue-electron` project with `electron-builder` as the packager.
2. Added library `fabric` to the project. `npm install fabric --save`.
3. `npm run dev` - works perfectly
4. `npm run build` - fails.

If I try the same 4 steps above with just a change to using `electron-packager`, all good.
Error when I try to build with `electron-builder` is as follows:

```
Error: /Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/bin/node exited with code 1
Output:

> contextify@0.1.15 install /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/fabric/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o

Error output:
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/abisheksrikaanth/.electron-gyp/.node-gyp/iojs-1.6.7/deps/v8/include/v8.h:3648:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/abisheksrikaanth/.electron-gyp/.node-gyp/iojs-1.6.7/deps/v8/include/v8.h:3220:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/abisheksrikaanth/.electron-gyp/.node-gyp/iojs-1.6.7/deps/v8/include/v8.h:3220:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/abisheksrikaanth/.electron-gyp/.node-gyp/iojs-1.6.7/deps/v8/include/v8.h:3220:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/bin/node" "/Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/fabric/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/bin/node" "/Users/abisheksrikaanth/.nvm/versions/node/v7.9.0/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "fsevents" "contextify" "canvas"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/abisheksrikaanth/.npm/_logs/2017-05-01T19_22_50_241Z-debug.log

    at ChildProcess.childProcess.once.code (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder-util/src/util.ts:134:14)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
From previous event:
    at spawn (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder-util/src/util.ts:97:3)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/yarn.ts:118:11
From previous event:
    at rebuild (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/yarn.js:87:22)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/yarn.js:33:21)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/packager.ts:305:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/packager.js:403:11)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/packager.ts:168:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/packager.js:299:11)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/packager.js:251:11)
    at /Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/Users/abisheksrikaanth/Viralstyle-Web-Projects/vsplus/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by SimulatedGREG** [comment]
Alright, I think I finally found a clean way to show the logs. Here here's what it looks like right now in the `dev` branch. Last thing to consider is the `friendly-errors-webpack-plugin` logging.

![image](https://cloud.githubusercontent.com/assets/8327811/25841404/91f2e040-3465-11e7-95a6-7bbce8666cd3.png)

**Comment by SimulatedGREG** [comment]
Good news, nearly all tasks for this Milestone are complete! There is still plenty of documentation to be updated, so until that is squared away a major push to `master` should be happening soon.

Currently looking to get started on project examples and featured community project. Please comment below any project examples you have in mind or submit your own electron-vue projects to get featured.

**Comment by SimulatedGREG** [comment]
### ✨ Checklist complete!

It looks like all items for this Milestone have been completed. Documentation has also been heavily overhauled to describe all of the new features. There are still a few things left on my personal task list to check out, but I will be planning to release merge to the `master` branch shortly after the `electron@1.7.2` release comes out. This release will support Node's Inspector Agent to make `main` process debugging a breeze.

A big thank you to everybody that has tried out the `dev` branch and provided generous feedback about issues and suggestions.

**Comment by SimulatedGREG** [comment]
In an attempt to implement versioning on scaffolded projects, there will be a new commit SHA link on the generated `README.md` file.

![image](https://cloud.githubusercontent.com/assets/8327811/26566530/705b3608-44b9-11e7-96e0-c358cc7a9fc5.png)

Shoutouts to @qazbnm456's [lulumi-browser](https://github.com/qazbnm456/lulumi-browser) for this idea.

**Comment by SimulatedGREG** [comment]
@rdpascua 

I'm aware of the `electron` restart issue. It seems I'm not getting a constant termination signal across platforms. Will be fixing this before release.

**Comment by SimulatedGREG** [comment]
# 🎉  It's Here! 🎉 

Milestone Minimize is officially in the `master` branch of this repo and can be used of course with...
```bash
vue init simulatedgreg/electron-vue my-project
```

There has been quite a number of changes, so make sure to take a look at the updated documentation to find out more about the new **single** `package.json` structure and some new features like the `__static` global variable.

Commit: https://github.com/SimulatedGREG/electron-vue/commit/2c29ea1b55bdb24ac625f57466e5aac3c366681a
Documentation: https://simulatedgreg.gitbooks.io/electron-vue/content/index.html
CI Test: https://semaphoreci.com/simulatedgreg/electron-vue/branches/master/builds/216
